"""A small hand-curated dataset so the search engine is demoable offline,
without needing a GitHub token or a live crawl. Mirrors the shape of the
GitHub API so it flows through the same normalize/upsert path.
"""

SEED_REPOS = [
    {
        "id": 1, "owner": "redis", "name": "redis",
        "description": "Redis is an in-memory database that persists on disk. Data structure store used as database, cache, and message broker.",
        "language": "C", "stars": 65000, "forks": 23500,
        "topics": ["database", "cache", "key-value", "in-memory", "nosql", "distributed"],
        "pushed_at": "2026-06-20T10:00:00Z",
    },
    {
        "id": 2, "owner": "etcd-io", "name": "etcd",
        "description": "Distributed reliable key-value store for the most critical data of a distributed system. Uses the Raft consensus algorithm.",
        "language": "Go", "stars": 47000, "forks": 9800,
        "topics": ["distributed-systems", "raft", "consensus", "key-value", "database"],
        "pushed_at": "2026-06-22T08:30:00Z",
    },
    {
        "id": 3, "owner": "apache", "name": "kafka",
        "description": "Distributed event streaming platform for high-throughput, fault-tolerant messaging and stream processing.",
        "language": "Java", "stars": 28000, "forks": 13800,
        "topics": ["distributed-systems", "streaming", "messaging", "event-driven", "pubsub"],
        "pushed_at": "2026-06-24T12:00:00Z",
    },
    {
        "id": 4, "owner": "tikv", "name": "tikv",
        "description": "Distributed transactional key-value database, originally created to complement TiDB. Built in Rust with Raft.",
        "language": "Rust", "stars": 15000, "forks": 2100,
        "topics": ["distributed-systems", "database", "key-value", "raft", "transactions"],
        "pushed_at": "2026-05-30T09:15:00Z",
    },
    {
        "id": 5, "owner": "tikv", "name": "raft-rs",
        "description": "Raft distributed consensus algorithm implemented in Rust.",
        "language": "Rust", "stars": 3000, "forks": 450,
        "topics": ["raft", "consensus", "distributed-systems"],
        "pushed_at": "2026-03-10T09:15:00Z",
    },
    {
        "id": 6, "owner": "tiangolo", "name": "fastapi",
        "description": "FastAPI framework, high performance, easy to learn, fast to code, ready for production. Modern Python web APIs.",
        "language": "Python", "stars": 78000, "forks": 6600,
        "topics": ["fastapi", "python", "web", "api", "rest", "async", "backend"],
        "pushed_at": "2026-06-25T14:00:00Z",
    },
    {
        "id": 7, "owner": "encode", "name": "django-rest-framework",
        "description": "Web APIs for Django. A powerful and flexible toolkit for building REST APIs with PostgreSQL support.",
        "language": "Python", "stars": 28000, "forks": 7000,
        "topics": ["django", "python", "rest", "api", "backend", "postgresql"],
        "pushed_at": "2026-06-18T11:00:00Z",
    },
    {
        "id": 8, "owner": "sqlalchemy", "name": "sqlalchemy",
        "description": "The Database Toolkit for Python. SQL toolkit and Object Relational Mapper supporting PostgreSQL, MySQL, SQLite.",
        "language": "Python", "stars": 9500, "forks": 1500,
        "topics": ["python", "orm", "sql", "database", "postgresql", "backend"],
        "pushed_at": "2026-06-15T16:20:00Z",
    },
    {
        "id": 9, "owner": "fullstack-demo", "name": "fastapi-postgres-starter",
        "description": "A beginner-friendly starter template for building backend applications with FastAPI and PostgreSQL, including auth and migrations.",
        "language": "Python", "stars": 850, "forks": 210,
        "topics": ["fastapi", "postgresql", "backend", "starter", "beginner-friendly", "tutorial"],
        "pushed_at": "2026-04-02T10:00:00Z",
    },
    {
        "id": 10, "owner": "gin-gonic", "name": "gin",
        "description": "Gin is a HTTP web framework written in Go. Fast, lightweight backend framework with a martini-like API.",
        "language": "Go", "stars": 77000, "forks": 8000,
        "topics": ["go", "web", "framework", "backend", "http", "api"],
        "pushed_at": "2026-06-10T09:00:00Z",
    },
    {
        "id": 11, "owner": "opencv", "name": "opencv",
        "description": "Open Source Computer Vision Library. Real-time computer vision for image processing and machine learning.",
        "language": "C++", "stars": 79000, "forks": 56000,
        "topics": ["computer-vision", "opencv", "image-processing", "machine-learning", "deep-learning"],
        "pushed_at": "2026-06-21T13:00:00Z",
    },
    {
        "id": 12, "owner": "ultralytics", "name": "yolov5",
        "description": "YOLOv5 object detection models for computer vision, with easy export and deployment to ONNX, CoreML, TFLite.",
        "language": "Python", "stars": 50000, "forks": 16000,
        "topics": ["computer-vision", "object-detection", "deep-learning", "deployment", "onnx", "pytorch"],
        "pushed_at": "2026-06-19T08:00:00Z",
    },
    {
        "id": 13, "owner": "roboflow", "name": "supervision",
        "description": "Reusable computer vision tools for deployment: detection, tracking, and annotation. Production-ready CV utilities.",
        "language": "Python", "stars": 18000, "forks": 1400,
        "topics": ["computer-vision", "deep-learning", "deployment", "object-detection", "tracking"],
        "pushed_at": "2026-06-23T10:30:00Z",
    },
    {
        "id": 14, "owner": "pytorch", "name": "pytorch",
        "description": "Tensors and dynamic neural networks in Python with strong GPU acceleration. Deep learning framework.",
        "language": "Python", "stars": 80000, "forks": 21000,
        "topics": ["deep-learning", "machine-learning", "neural-networks", "gpu", "python", "tensors"],
        "pushed_at": "2026-06-25T17:00:00Z",
    },
    {
        "id": 15, "owner": "huggingface", "name": "transformers",
        "description": "State-of-the-art machine learning for PyTorch, TensorFlow, and JAX. Pretrained models for NLP and computer vision.",
        "language": "Python", "stars": 130000, "forks": 26000,
        "topics": ["machine-learning", "nlp", "deep-learning", "transformers", "pytorch", "computer-vision"],
        "pushed_at": "2026-06-26T09:00:00Z",
    },
    {
        "id": 16, "owner": "facebook", "name": "react",
        "description": "The library for web and native user interfaces. Declarative, component-based JavaScript UI library.",
        "language": "JavaScript", "stars": 225000, "forks": 46000,
        "topics": ["react", "javascript", "frontend", "ui", "library"],
        "pushed_at": "2026-06-24T15:00:00Z",
    },
    {
        "id": 17, "owner": "vercel", "name": "next.js",
        "description": "The React Framework for the Web. Full-stack React applications with server-side rendering and static generation.",
        "language": "JavaScript", "stars": 122000, "forks": 26000,
        "topics": ["react", "nextjs", "frontend", "fullstack", "ssr", "javascript"],
        "pushed_at": "2026-06-25T11:00:00Z",
    },
    {
        "id": 18, "owner": "kubernetes", "name": "kubernetes",
        "description": "Production-grade container orchestration. Automated deployment, scaling, and management of containerized applications.",
        "language": "Go", "stars": 108000, "forks": 39000,
        "topics": ["kubernetes", "containers", "orchestration", "distributed-systems", "cloud", "devops"],
        "pushed_at": "2026-06-26T08:00:00Z",
    },
    {
        "id": 19, "owner": "grafana", "name": "grafana",
        "description": "The open and composable observability and data visualization platform. Metrics, logs, and dashboards.",
        "language": "Go", "stars": 62000, "forks": 12000,
        "topics": ["monitoring", "observability", "dashboards", "metrics", "visualization", "devops"],
        "pushed_at": "2026-06-22T14:00:00Z",
    },
    {
        "id": 20, "owner": "prometheus", "name": "prometheus",
        "description": "The Prometheus monitoring system and time series database for reliable metrics collection in distributed systems.",
        "language": "Go", "stars": 55000, "forks": 9000,
        "topics": ["monitoring", "metrics", "time-series", "distributed-systems", "observability"],
        "pushed_at": "2026-06-20T10:00:00Z",
    },
    {
        "id": 21, "owner": "postgres", "name": "postgres",
        "description": "Mirror of the PostgreSQL relational database. Powerful, open source object-relational database system.",
        "language": "C", "stars": 16000, "forks": 4600,
        "topics": ["postgresql", "database", "sql", "relational"],
        "pushed_at": "2026-06-24T07:00:00Z",
    },
    {
        "id": 22, "owner": "minio", "name": "minio",
        "description": "High performance, S3 compatible object storage. Distributed object storage server for cloud-native workloads.",
        "language": "Go", "stars": 48000, "forks": 5500,
        "topics": ["object-storage", "s3", "distributed-systems", "cloud", "storage"],
        "pushed_at": "2026-06-17T09:00:00Z",
    },
    {
        "id": 23, "owner": "learn-backend", "name": "build-your-own-redis",
        "description": "A beginner-friendly tutorial project to build your own Redis clone from scratch in Python. Great for learning systems programming.",
        "language": "Python", "stars": 1200, "forks": 320,
        "topics": ["redis", "tutorial", "beginner-friendly", "backend", "systems", "learning"],
        "pushed_at": "2026-02-14T09:00:00Z",
    },
    {
        "id": 24, "owner": "tutorials", "name": "distributed-systems-101",
        "description": "A beginner-friendly collection of distributed systems projects and exercises: build a key-value store, implement raft, and more.",
        "language": "Go", "stars": 2400, "forks": 410,
        "topics": ["distributed-systems", "beginner-friendly", "tutorial", "raft", "learning", "backend"],
        "pushed_at": "2026-05-01T09:00:00Z",
    },
    {
        "id": 25, "owner": "celery", "name": "celery",
        "description": "Distributed task queue. Asynchronous job processing for Python with Redis and RabbitMQ backends.",
        "language": "Python", "stars": 25000, "forks": 4700,
        "topics": ["python", "task-queue", "distributed-systems", "async", "backend", "redis"],
        "pushed_at": "2026-06-12T10:00:00Z",
    },
    {
        "id": 26, "owner": "dragonflydb", "name": "dragonfly",
        "description": "A modern replacement for Redis and Memcached. In-memory data store built for scale and high throughput.",
        "language": "C++", "stars": 26000, "forks": 980,
        "topics": ["redis", "in-memory", "database", "cache", "key-value", "distributed"],
        "pushed_at": "2026-06-23T11:00:00Z",
    },
    {
        "id": 27, "owner": "valkey-io", "name": "valkey",
        "description": "A flexible distributed key-value datastore that supports caching and beyond. A community fork of Redis.",
        "language": "C", "stars": 20000, "forks": 800,
        "topics": ["redis", "key-value", "cache", "in-memory", "database", "distributed"],
        "pushed_at": "2026-06-25T13:00:00Z",
    },
    {
        "id": 28, "owner": "fastapi-users", "name": "fastapi-users",
        "description": "Ready-to-use and customizable user authentication for FastAPI applications, with database adapters for PostgreSQL.",
        "language": "Python", "stars": 4800, "forks": 540,
        "topics": ["fastapi", "authentication", "postgresql", "backend", "python", "api"],
        "pushed_at": "2026-05-20T10:00:00Z",
    },
    {
        "id": 29, "owner": "detectron", "name": "detectron2",
        "description": "Facebook AI Research's next-generation library for object detection and segmentation in computer vision.",
        "language": "Python", "stars": 31000, "forks": 7600,
        "topics": ["computer-vision", "object-detection", "deep-learning", "segmentation", "pytorch"],
        "pushed_at": "2026-04-15T10:00:00Z",
    },
    {
        "id": 30, "owner": "old-projects", "name": "legacy-image-classifier",
        "description": "An older computer vision image classification project. No longer maintained.",
        "language": "Python", "stars": 600, "forks": 120,
        "topics": ["computer-vision", "image-classification", "deep-learning"],
        "pushed_at": "2022-01-10T10:00:00Z",
    },
]


def to_api_shape(repo: dict) -> dict:
    """Convert a seed entry to the GitHub-API-like shape upsert_repository expects."""
    return {
        "id": repo["id"],
        "name": repo["name"],
        "full_name": f"{repo['owner']}/{repo['name']}",
        "owner": {"login": repo["owner"]},
        "description": repo["description"],
        "language": repo["language"],
        "stargazers_count": repo["stars"],
        "forks_count": repo["forks"],
        "open_issues_count": 0,
        "watchers_count": repo["stars"],
        "license": None,
        "homepage": None,
        "html_url": f"https://github.com/{repo['owner']}/{repo['name']}",
        "fork": False,
        "archived": False,
        "topics": repo["topics"],
        "pushed_at": repo["pushed_at"],
        "created_at": repo["pushed_at"],
        "updated_at": repo["pushed_at"],
    }
